CREATE TABLE IF NOT EXISTS agent_event_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  event_id VARCHAR(64) NOT NULL COMMENT '事件ID',
  event_time DATETIME(3) NOT NULL COMMENT '事件时间',
  event_time_ms BIGINT NOT NULL COMMENT '事件时间毫秒',
  event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
  level VARCHAR(16) NULL COMMENT '事件级别',
  machine_tag VARCHAR(128) NULL COMMENT '机器标识',
  agent_session_id VARCHAR(128) NULL COMMENT 'Agent会话ID',
  state_version BIGINT NULL COMMENT 'Agent状态版本',
  task_id BIGINT NULL COMMENT '任务ID',
  execute_id BIGINT NULL COMMENT '执行ID',
  dispatch_token VARCHAR(64) NULL COMMENT '下发令牌',
  request_id VARCHAR(128) NULL COMMENT '请求ID',
  command TEXT NULL COMMENT '完整命令',
  message VARCHAR(1024) NULL COMMENT '事件消息',
  detail TEXT NULL COMMENT '事件详情',
  duration_ms BIGINT NULL COMMENT '耗时毫秒',
  error_type VARCHAR(256) NULL COMMENT '异常类型',
  error_message TEXT NULL COMMENT '异常消息',
  server VARCHAR(128) NULL COMMENT 'Server地址',
  thread VARCHAR(128) NULL COMMENT 'Agent线程',
  gmt_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_event_id (event_id),
  KEY idx_event_time (event_time_ms),
  KEY idx_machine_time (machine_tag, event_time_ms),
  KEY idx_request_time (request_id, event_time_ms),
  KEY idx_task_execute_time (task_id, execute_id, event_time_ms),
  KEY idx_event_type_time (event_type, event_time_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent关键事件日志';
